// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_tokens.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertAgentToken = `-- name: InsertAgentToken :one
INSERT INTO agent_tokens (subject, label, token_hash)
VALUES ($1, $2, $3)
RETURNING id, subject, label, created_at
`

type InsertAgentTokenParams struct {
	Subject   string
	Label     string
	TokenHash []byte
}

type InsertAgentTokenRow struct {
	ID        string
	Subject   string
	Label     string
	CreatedAt time.Time
}

func (q *Queries) InsertAgentToken(ctx context.Context, arg InsertAgentTokenParams) (InsertAgentTokenRow, error) {
	row := q.db.QueryRow(ctx, insertAgentToken, arg.Subject, arg.Label, arg.TokenHash)
	var i InsertAgentTokenRow
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentTokens = `-- name: ListAgentTokens :many
SELECT id, subject, label, created_at, last_used_at, revoked_at FROM agent_tokens ORDER BY created_at ASC
`

type ListAgentTokensRow struct {
	ID         string
	Subject    string
	Label      string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

func (q *Queries) ListAgentTokens(ctx context.Context) ([]ListAgentTokensRow, error) {
	rows, err := q.db.Query(ctx, listAgentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentTokensRow
	for rows.Next() {
		var i ListAgentTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupActiveAgentToken = `-- name: LookupActiveAgentToken :one
SELECT id, subject, label FROM agent_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

type LookupActiveAgentTokenRow struct {
	ID      string
	Subject string
	Label   string
}

func (q *Queries) LookupActiveAgentToken(ctx context.Context, tokenHash []byte) (LookupActiveAgentTokenRow, error) {
	row := q.db.QueryRow(ctx, lookupActiveAgentToken, tokenHash)
	var i LookupActiveAgentTokenRow
	err := row.Scan(&i.ID, &i.Subject, &i.Label)
	return i, err
}

const revokeAgentToken = `-- name: RevokeAgentToken :execrows
UPDATE agent_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAgentToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAgentToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAgentToken = `-- name: TouchAgentToken :exec
UPDATE agent_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAgentToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAgentToken, id)
	return err
}
