// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (event_type, subject, fact_id, grant_id, staged_diff_id, scopes)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	EventType    string
	Subject      string
	FactID       *string
	GrantID      *string
	StagedDiffID *string
	Scopes       []string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.EventType,
		arg.Subject,
		arg.FactID,
		arg.GrantID,
		arg.StagedDiffID,
		arg.Scopes,
	)
	return err
}
