// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: data_keys.sql

package sqlcgen

import (
	"context"
)

const getDataKey = `-- name: GetDataKey :one
SELECT purpose, wrapped_key, created_at, rotated_at FROM data_keys WHERE purpose = $1
`

func (q *Queries) GetDataKey(ctx context.Context, purpose string) (DataKey, error) {
	row := q.db.QueryRow(ctx, getDataKey, purpose)
	var i DataKey
	err := row.Scan(
		&i.Purpose,
		&i.WrappedKey,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const insertDataKey = `-- name: InsertDataKey :one
INSERT INTO data_keys (purpose, wrapped_key)
VALUES ($1, $2)
ON CONFLICT (purpose) DO NOTHING
RETURNING purpose, wrapped_key, created_at, rotated_at
`

type InsertDataKeyParams struct {
	Purpose    string
	WrappedKey []byte
}

// ON CONFLICT DO NOTHING rather than an upsert: two processes booting at once
// must not each mint a DEK and have the second overwrite the first, because
// anything the loser sealed in between would become unopenable. The conflicting
// caller gets no row back and re-reads the winner's key instead — see
// LoadOrCreateDataKey.
func (q *Queries) InsertDataKey(ctx context.Context, arg InsertDataKeyParams) (DataKey, error) {
	row := q.db.QueryRow(ctx, insertDataKey, arg.Purpose, arg.WrappedKey)
	var i DataKey
	err := row.Scan(
		&i.Purpose,
		&i.WrappedKey,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const rewrapDataKey = `-- name: RewrapDataKey :execrows
UPDATE data_keys SET wrapped_key = $2, rotated_at = now() WHERE purpose = $1
`

type RewrapDataKeyParams struct {
	Purpose    string
	WrappedKey []byte
}

// Master-key rotation: replaces the wrapping without touching anything sealed
// under the DEK itself. The DEK's plaintext bytes are unchanged by definition,
// so no data is re-encrypted.
func (q *Queries) RewrapDataKey(ctx context.Context, arg RewrapDataKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, rewrapDataKey, arg.Purpose, arg.WrappedKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
