// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment_latch.sql

package sqlcgen

import (
	"context"
)

const enrollmentLatchSet = `-- name: EnrollmentLatchSet :one
SELECT EXISTS(SELECT 1 FROM enrollment_latch) AS latched
`

// The durable half of createToken's enrollment gate. Unlike
// CountEverEnrolledReviewerTokens/CountEverEnrolledWebAuthnCredentials, which
// read mutable factor rows the break-glass recovery clears, this survives a
// factor reset — so the gate stays closed against a factorless bootstrap or a
// stolen bearer token racing the operator during re-enrollment.
func (q *Queries) EnrollmentLatchSet(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, enrollmentLatchSet)
	var latched bool
	err := row.Scan(&latched)
	return latched, err
}

const setEnrollmentLatch = `-- name: SetEnrollmentLatch :exec
INSERT INTO enrollment_latch (id) VALUES (true) ON CONFLICT (id) DO NOTHING
`

// Idempotent set-once: the first enrollment inserts the singleton row, every
// later one conflicts on the pinned primary key and does nothing — latched_at
// is never re-stamped, and no second row is ever created. Deliberately never
// an UPDATE/DELETE path: the latch only ever goes from unset to set over the
// lifetime of a deployment (principle 12), so clearing it is an out-of-band
// operator action, not something any store method exposes.
func (q *Queries) SetEnrollmentLatch(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setEnrollmentLatch)
	return err
}
