// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grant_requests.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveGrantRequest = `-- name: ApproveGrantRequest :execrows
UPDATE grant_requests
SET status = 'approved', decided_at = now(), decided_by = $2, resulting_grant_id = $3
WHERE id = $1 AND status = 'pending'
`

type ApproveGrantRequestParams struct {
	ID               string
	DecidedBy        *string
	ResultingGrantID *string
}

func (q *Queries) ApproveGrantRequest(ctx context.Context, arg ApproveGrantRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveGrantRequest, arg.ID, arg.DecidedBy, arg.ResultingGrantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const denyGrantRequest = `-- name: DenyGrantRequest :execrows
UPDATE grant_requests SET status = 'denied', decided_at = now(), decided_by = $2
WHERE id = $1 AND status = 'pending'
`

type DenyGrantRequestParams struct {
	ID        string
	DecidedBy *string
}

func (q *Queries) DenyGrantRequest(ctx context.Context, arg DenyGrantRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, denyGrantRequest, arg.ID, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGrantRequest = `-- name: GetGrantRequest :one
SELECT id, subject, requested_scopes, depth, requested_ttl_seconds, justification, status, created_at, decided_at, decided_by, resulting_grant_id, kind
FROM grant_requests WHERE id = $1
`

func (q *Queries) GetGrantRequest(ctx context.Context, id string) (GrantRequest, error) {
	row := q.db.QueryRow(ctx, getGrantRequest, id)
	var i GrantRequest
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.RequestedScopes,
		&i.Depth,
		&i.RequestedTtlSeconds,
		&i.Justification,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.ResultingGrantID,
		&i.Kind,
	)
	return i, err
}

const insertGrantRequest = `-- name: InsertGrantRequest :one
INSERT INTO grant_requests (subject, requested_scopes, kind, depth, requested_ttl_seconds, justification)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, status, created_at
`

type InsertGrantRequestParams struct {
	Subject             string
	RequestedScopes     []string
	Kind                string
	Depth               *string
	RequestedTtlSeconds pgtype.Int4
	Justification       string
}

type InsertGrantRequestRow struct {
	ID        string
	Status    string
	CreatedAt time.Time
}

// Database-generated columns only; see InsertStagedDiff for why. The rest is
// the caller's own input, and returning `justification` in particular meant the
// agent role needed SELECT over every subject's stated reasons for wanting a
// grant.
func (q *Queries) InsertGrantRequest(ctx context.Context, arg InsertGrantRequestParams) (InsertGrantRequestRow, error) {
	row := q.db.QueryRow(ctx, insertGrantRequest,
		arg.Subject,
		arg.RequestedScopes,
		arg.Kind,
		arg.Depth,
		arg.RequestedTtlSeconds,
		arg.Justification,
	)
	var i InsertGrantRequestRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const listGrantRequests = `-- name: ListGrantRequests :many
SELECT id, subject, requested_scopes, depth, requested_ttl_seconds, justification, status, created_at, decided_at, decided_by, resulting_grant_id, kind
FROM grant_requests WHERE status = $1 ORDER BY created_at ASC
`

func (q *Queries) ListGrantRequests(ctx context.Context, status string) ([]GrantRequest, error) {
	rows, err := q.db.Query(ctx, listGrantRequests, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrantRequest
	for rows.Next() {
		var i GrantRequest
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.RequestedScopes,
			&i.Depth,
			&i.RequestedTtlSeconds,
			&i.Justification,
			&i.Status,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.ResultingGrantID,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadGrantRequestForUpdate = `-- name: LoadGrantRequestForUpdate :one
SELECT subject, requested_scopes, depth, requested_ttl_seconds, status, kind FROM grant_requests WHERE id = $1 FOR UPDATE
`

type LoadGrantRequestForUpdateRow struct {
	Subject             string
	RequestedScopes     []string
	Depth               *string
	RequestedTtlSeconds pgtype.Int4
	Status              string
	Kind                string
}

func (q *Queries) LoadGrantRequestForUpdate(ctx context.Context, id string) (LoadGrantRequestForUpdateRow, error) {
	row := q.db.QueryRow(ctx, loadGrantRequestForUpdate, id)
	var i LoadGrantRequestForUpdateRow
	err := row.Scan(
		&i.Subject,
		&i.RequestedScopes,
		&i.Depth,
		&i.RequestedTtlSeconds,
		&i.Status,
		&i.Kind,
	)
	return i, err
}
