// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const grantedScopeDepths = `-- name: GrantedScopeDepths :many
SELECT DISTINCT gs.scope, g.depth
FROM grant_scopes gs
JOIN grants g ON g.id = gs.grant_id
WHERE g.subject = $1
  AND g.kind = 'memory'
  AND g.depth IS NOT NULL
  AND g.revoked_at IS NULL
  AND (g.expires_at IS NULL OR g.expires_at > now())
`

type GrantedScopeDepthsRow struct {
	Scope string
	Depth *string
}

// depth IS NOT NULL is implied by kind = 'memory' (the grants_kind_depth_pairing
// CHECK constraint), restated here rather than relied on so this query's own
// WHERE clause is self-documenting independent of that constraint existing
// elsewhere.
func (q *Queries) GrantedScopeDepths(ctx context.Context, subject string) ([]GrantedScopeDepthsRow, error) {
	rows, err := q.db.Query(ctx, grantedScopeDepths, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrantedScopeDepthsRow
	for rows.Next() {
		var i GrantedScopeDepthsRow
		if err := rows.Scan(&i.Scope, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantedScopes = `-- name: GrantedScopes :many
SELECT DISTINCT gs.scope
FROM grant_scopes gs
JOIN grants g ON g.id = gs.grant_id
WHERE g.subject = $1
  AND g.kind = 'memory'
  AND g.revoked_at IS NULL
  AND (g.expires_at IS NULL OR g.expires_at > now())
`

// kind = 'memory' excludes capability-only grants (e.g. git.sign:...) from
// authorizing memory reads/writes over the same scope string — see
// store.GrantedScopes' doc comment.
func (q *Queries) GrantedScopes(ctx context.Context, subject string) ([]string, error) {
	rows, err := q.db.Query(ctx, grantedScopes, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var scope string
		if err := rows.Scan(&scope); err != nil {
			return nil, err
		}
		items = append(items, scope)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGrant = `-- name: InsertGrant :one
INSERT INTO grants (subject, kind, depth, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, subject, depth, created_at, expires_at, revoked_at, kind
`

type InsertGrantParams struct {
	Subject   string
	Kind      string
	Depth     *string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) (Grant, error) {
	row := q.db.QueryRow(ctx, insertGrant,
		arg.Subject,
		arg.Kind,
		arg.Depth,
		arg.ExpiresAt,
	)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Depth,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Kind,
	)
	return i, err
}

const insertGrantScope = `-- name: InsertGrantScope :exec
INSERT INTO grant_scopes (grant_id, scope) VALUES ($1, $2)
`

type InsertGrantScopeParams struct {
	GrantID string
	Scope   string
}

func (q *Queries) InsertGrantScope(ctx context.Context, arg InsertGrantScopeParams) error {
	_, err := q.db.Exec(ctx, insertGrantScope, arg.GrantID, arg.Scope)
	return err
}

const listGrantScopes = `-- name: ListGrantScopes :many
SELECT scope FROM grant_scopes WHERE grant_id = $1
`

func (q *Queries) ListGrantScopes(ctx context.Context, grantID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listGrantScopes, grantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var scope string
		if err := rows.Scan(&scope); err != nil {
			return nil, err
		}
		items = append(items, scope)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many
SELECT g.id, g.subject, g.depth, g.created_at, g.expires_at, g.revoked_at, g.kind,
       (SELECT array_agg(gs.scope) FROM grant_scopes gs WHERE gs.grant_id = g.id)::text[] AS scopes
FROM grants g WHERE g.subject = $1 ORDER BY g.created_at DESC
`

type ListGrantsRow struct {
	ID        string
	Subject   string
	Depth     *string
	CreatedAt time.Time
	ExpiresAt *time.Time
	RevokedAt *time.Time
	Kind      string
	Scopes    []string
}

// Unpaginated, subject-scoped by design: this is also what
// internal/mcptools/list_grants.go's list_grants tool calls for an agent to
// list its own grants, a small result set by construction — not the
// reviewer-facing "list everything" surface the pagination ticket is about.
// ListGrantsPage (below) is the paginated sibling used by GET /api/grants.
// Scopes come back via an array_agg subquery (same shape as
// ListGrantsNearingExpiry and GetFact/SearchFacts' fact_scopes aggregation in
// facts.sql) rather than a separate ListGrantScopes call per row, to avoid an
// N+1 query per returned grant. Found in review.
func (q *Queries) ListGrants(ctx context.Context, subject string) ([]ListGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGrants, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsRow
	for rows.Next() {
		var i ListGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Depth,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Kind,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsNearingExpiry = `-- name: ListGrantsNearingExpiry :many
SELECT g.id, g.subject, g.depth, g.created_at, g.expires_at, g.revoked_at, g.kind,
       (SELECT array_agg(gs.scope) FROM grant_scopes gs WHERE gs.grant_id = g.id)::text[] AS scopes
FROM grants g
WHERE g.revoked_at IS NULL
  AND g.expires_at IS NOT NULL
  AND g.expires_at > now()
  AND g.expires_at <= $1
ORDER BY g.expires_at ASC
`

type ListGrantsNearingExpiryRow struct {
	ID        string
	Subject   string
	Depth     *string
	CreatedAt time.Time
	ExpiresAt *time.Time
	RevokedAt *time.Time
	Kind      string
	Scopes    []string
}

// Subject-agnostic by design, like ListStagedDiffs/ListGrantRequests — v0 is a
// single-operator system (AGENTS.md), so the expiry-warning SSE stream isn't
// scoped per subject either.
//
// Scopes come back via an array_agg subquery (same shape as GetFact/
// SearchFacts' fact_scopes aggregation in facts.sql) rather than a separate
// ListGrantScopes call per row: this query runs from the /api/events poll
// loop, potentially every eventPollInterval per connected SSE client, so an
// N+1 pattern here scales with (expiring grants) x (connected clients) x
// (polls/sec) — worth avoiding at the query level rather than in a hot loop.
// Found in review.
func (q *Queries) ListGrantsNearingExpiry(ctx context.Context, expiresAt pgtype.Timestamptz) ([]ListGrantsNearingExpiryRow, error) {
	rows, err := q.db.Query(ctx, listGrantsNearingExpiry, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsNearingExpiryRow
	for rows.Next() {
		var i ListGrantsNearingExpiryRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Depth,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Kind,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsPage = `-- name: ListGrantsPage :many
SELECT g.id, g.subject, g.depth, g.created_at, g.expires_at, g.revoked_at, g.kind,
       (SELECT array_agg(gs.scope) FROM grant_scopes gs WHERE gs.grant_id = g.id)::text[] AS scopes
FROM grants g
WHERE g.subject = $1
  AND ($2::timestamptz IS NULL
       OR (g.created_at, g.id) < ($2::timestamptz, $3::uuid))
ORDER BY g.created_at DESC, g.id DESC
LIMIT $4
`

type ListGrantsPageParams struct {
	Subject         string
	CursorCreatedAt *time.Time
	CursorID        *string
	Lim             int64
}

type ListGrantsPageRow struct {
	ID        string
	Subject   string
	Depth     *string
	CreatedAt time.Time
	ExpiresAt *time.Time
	RevokedAt *time.Time
	Kind      string
	Scopes    []string
}

// Cursor-paginated listing for GET /api/grants (internal/api/grants.go).
// Newest first, matching ListGrants' own ORDER BY, so the cursor comparison
// runs the opposite direction from ListStagedDiffsPage's oldest-first queue
// order (staged_diffs.sql): a page here is "every one of subject's grants
// strictly older than the last row already returned." Same (created_at, id)
// keyset rationale as ListStagedDiffsPage — see that query's doc comment.
// Scopes use the same array_agg subquery as ListGrants above, for the same
// N+1 reason.
func (q *Queries) ListGrantsPage(ctx context.Context, arg ListGrantsPageParams) ([]ListGrantsPageRow, error) {
	rows, err := q.db.Query(ctx, listGrantsPage,
		arg.Subject,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsPageRow
	for rows.Next() {
		var i ListGrantsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Depth,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Kind,
			&i.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewGrant = `-- name: RenewGrant :one
UPDATE grants SET expires_at = $2
WHERE id = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
  AND kind = 'memory'
RETURNING id, subject, depth, created_at, expires_at, revoked_at, kind
`

type RenewGrantParams struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
}

// Only a currently-active grant (not revoked, not already past its expiry) can
// be renewed — zero rows affected (surfaced by sqlc as pgx.ErrNoRows for a
// :one query) covers "doesn't exist," "already revoked," and "already
// expired" alike; store.RenewGrant turns that into one clear error.
//
// kind = 'memory' is deliberate, not incidental. Renewal was built for memory
// grants, and extending a *capability* grant is a materially different act:
// capability renewal has to answer what happens to key material held for the
// grant's duration, whether the custody backend must be reachable to renew,
// and whether a renewal is a fresh authorization decision rather than a date
// change. None of that is designed yet. Until the broker answers it, a
// capability grant is renewed by not being renewable — deliberately, rather
// than inheriting memory's semantics by omission. Nothing can create one
// today (both API and MCP hardcode kind='memory'), so this filter is a latch
// closed before the door exists, not a live fix.
func (q *Queries) RenewGrant(ctx context.Context, arg RenewGrantParams) (Grant, error) {
	row := q.db.QueryRow(ctx, renewGrant, arg.ID, arg.ExpiresAt)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Depth,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Kind,
	)
	return i, err
}

const revokeGrant = `-- name: RevokeGrant :execrows
UPDATE grants SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeGrant(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeGrant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
