// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const grantedScopes = `-- name: GrantedScopes :many
SELECT DISTINCT gs.scope
FROM grant_scopes gs
JOIN grants g ON g.id = gs.grant_id
WHERE g.subject = $1
  AND g.revoked_at IS NULL
  AND (g.expires_at IS NULL OR g.expires_at > now())
`

func (q *Queries) GrantedScopes(ctx context.Context, subject string) ([]string, error) {
	rows, err := q.db.Query(ctx, grantedScopes, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var scope string
		if err := rows.Scan(&scope); err != nil {
			return nil, err
		}
		items = append(items, scope)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGrant = `-- name: InsertGrant :one
INSERT INTO grants (subject, depth, expires_at)
VALUES ($1, $2, $3)
RETURNING id, subject, depth, created_at, expires_at, revoked_at
`

type InsertGrantParams struct {
	Subject   string
	Depth     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) (Grant, error) {
	row := q.db.QueryRow(ctx, insertGrant, arg.Subject, arg.Depth, arg.ExpiresAt)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Depth,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertGrantScope = `-- name: InsertGrantScope :exec
INSERT INTO grant_scopes (grant_id, scope) VALUES ($1, $2)
`

type InsertGrantScopeParams struct {
	GrantID string
	Scope   string
}

func (q *Queries) InsertGrantScope(ctx context.Context, arg InsertGrantScopeParams) error {
	_, err := q.db.Exec(ctx, insertGrantScope, arg.GrantID, arg.Scope)
	return err
}

const listGrantScopes = `-- name: ListGrantScopes :many
SELECT scope FROM grant_scopes WHERE grant_id = $1
`

func (q *Queries) ListGrantScopes(ctx context.Context, grantID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listGrantScopes, grantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var scope string
		if err := rows.Scan(&scope); err != nil {
			return nil, err
		}
		items = append(items, scope)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many
SELECT id, subject, depth, created_at, expires_at, revoked_at
FROM grants WHERE subject = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGrants(ctx context.Context, subject string) ([]Grant, error) {
	rows, err := q.db.Query(ctx, listGrants, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grant
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Depth,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGrant = `-- name: RevokeGrant :execrows
UPDATE grants SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeGrant(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeGrant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
