// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	pgvector "github.com/pgvector/pgvector-go"
)

type AuditLog struct {
	ID           string
	EventType    string
	Subject      string
	FactID       *string
	GrantID      *string
	StagedDiffID *string
	Scopes       []string
	Detail       []byte
	CreatedAt    time.Time
}

type Fact struct {
	ID                 string
	Content            string
	Embedding          *pgvector.Vector
	ContentTsv         interface{}
	Metadata           []byte
	SourceStagedDiffID string
	SupersededBy       *string
	CreatedAt          time.Time
	ValidAt            time.Time
	InvalidAt          *time.Time
	ExpiredAt          *time.Time
}

type FactScope struct {
	FactID string
	Scope  string
}

type Grant struct {
	ID        string
	Subject   string
	Depth     string
	CreatedAt time.Time
	ExpiresAt *time.Time
	RevokedAt *time.Time
}

type GrantScope struct {
	GrantID string
	Scope   string
}

type ReviewerToken struct {
	ID         string
	Label      string
	TokenHash  []byte
	CreatedAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type StagedDiff struct {
	ID                    string
	Subject               string
	Content               string
	ProposedScopes        []string
	TargetFactID          *string
	Status                string
	DedupeVerdict         *string
	DedupeCandidateFactID *string
	CreatedAt             time.Time
	DecidedAt             *time.Time
	DecidedBy             *string
}
