// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type AgentToken struct {
	ID         string
	Subject    string
	Label      string
	TokenHash  []byte
	CreatedAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type AuditLog struct {
	ID             string
	EventType      string
	Subject        string
	FactID         *string
	GrantID        *string
	StagedDiffID   *string
	Scopes         []string
	Detail         []byte
	CreatedAt      time.Time
	GrantRequestID *string
}

type CapabilityGrantIdentity struct {
	GrantID        string
	CommitterEmail string
	CreatedAt      time.Time
}

type CapabilityGrantToken struct {
	GrantID   string
	TokenHash []byte
	CreatedAt time.Time
}

type DataKey struct {
	Purpose    string
	WrappedKey []byte
	CreatedAt  time.Time
	RotatedAt  *time.Time
}

type EnrollmentLatch struct {
	ID        bool
	LatchedAt time.Time
}

type Fact struct {
	ID                 string
	Content            string
	Embedding          *pgvector.Vector
	ContentTsv         interface{}
	Metadata           []byte
	SourceStagedDiffID string
	SupersededBy       *string
	CreatedAt          time.Time
	ValidAt            time.Time
	InvalidAt          *time.Time
	ExpiredAt          *time.Time
	Summary            *string
}

type FactScope struct {
	FactID string
	Scope  string
}

type Grant struct {
	ID        string
	Subject   string
	Depth     *string
	CreatedAt time.Time
	ExpiresAt *time.Time
	RevokedAt *time.Time
	Kind      string
}

type GrantRequest struct {
	ID                  string
	Subject             string
	RequestedScopes     []string
	Depth               *string
	RequestedTtlSeconds pgtype.Int4
	Justification       string
	Status              string
	CreatedAt           time.Time
	DecidedAt           *time.Time
	DecidedBy           *string
	ResultingGrantID    *string
	Kind                string
}

type GrantScope struct {
	GrantID string
	Scope   string
}

type ProposeWriteRateLimit struct {
	Subject     string
	WindowStart time.Time
	Count       int32
}

type ReviewerToken struct {
	ID            string
	Label         string
	TokenHash     []byte
	CreatedAt     time.Time
	LastUsedAt    *time.Time
	RevokedAt     *time.Time
	TotpSecretEnc []byte
}

type SigningPolicy struct {
	Repo      string
	Policy    string
	SetBy     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type StagedDiff struct {
	ID                    string
	Subject               string
	Content               string
	ProposedScopes        []string
	TargetFactID          *string
	Status                string
	DedupeVerdict         *string
	DedupeCandidateFactID *string
	CreatedAt             time.Time
	DecidedAt             *time.Time
	DecidedBy             *string
}

type WebauthnChallenge struct {
	ID              string
	ReviewerTokenID string
	Purpose         string
	SessionData     []byte
	ExpiresAt       time.Time
	CreatedAt       time.Time
}

type WebauthnCredential struct {
	ID              string
	ReviewerTokenID string
	Label           string
	CredentialID    []byte
	PublicKey       []byte
	AttestationType string
	Transports      []string
	Aaguid          []byte
	SignCount       int64
	BackupEligible  bool
	BackupState     bool
	CreatedAt       time.Time
	LastUsedAt      *time.Time
	CloneWarningAt  *time.Time
	RevokedAt       *time.Time
}
