// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApproveGrantRequest(ctx context.Context, arg ApproveGrantRequestParams) (int64, error)
	CountActiveReviewerTokens(ctx context.Context) (int64, error)
	// Deliberately NOT filtered on revoked_at: this counts whether a TOTP device
	// has *ever* been enrolled, which is a monotonic, attacker-unlowerable signal.
	// Counting only active tokens made revocation (bearer-only by design, since it
	// "only reduces authority") into an escalation lever: revoke every enrolled
	// device, drop the count to zero, then mint a fresh token and self-enroll
	// through the now-open gate. Revoked rows are never deleted, so this count
	// only ever grows. See createToken (internal/api/tokens.go).
	CountEverEnrolledReviewerTokens(ctx context.Context) (int64, error)
	DenyGrantRequest(ctx context.Context, arg DenyGrantRequestParams) (int64, error)
	FactVisibleToScopes(ctx context.Context, arg FactVisibleToScopesParams) (bool, error)
	// embedding_1/embedding_2 are the same repeated-named-param workaround used
	// elsewhere in this migration (see facts.sql's SearchFacts) — bound to the
	// identical value at the call site.
	FindDedupeCandidate(ctx context.Context, arg FindDedupeCandidateParams) (FindDedupeCandidateRow, error)
	GetDataKey(ctx context.Context, purpose string) (DataKey, error)
	GetFact(ctx context.Context, id string) (GetFactRow, error)
	GetGrantRequest(ctx context.Context, id string) (GrantRequest, error)
	GetReviewerTOTPSecret(ctx context.Context, id string) ([]byte, error)
	GetStagedDiff(ctx context.Context, id string) (StagedDiff, error)
	// depth IS NOT NULL is implied by kind = 'memory' (the grants_kind_depth_pairing
	// CHECK constraint), restated here rather than relied on so this query's own
	// WHERE clause is self-documenting independent of that constraint existing
	// elsewhere.
	GrantedScopeDepths(ctx context.Context, subject string) ([]GrantedScopeDepthsRow, error)
	// kind = 'memory' excludes capability-only grants (e.g. git.sign:...) from
	// authorizing memory reads/writes over the same scope string — see
	// store.GrantedScopes' doc comment.
	GrantedScopes(ctx context.Context, subject string) ([]string, error)
	// Two distinct named params bound to the identical exclude-fact-ID value at the
	// call site (see staged_diffs.go) — sqlc's parser doesn't handle referencing the
	// same named param twice cleanly in this position (same issue worked around in
	// facts.sql's SearchFacts).
	HasActiveDuplicateContent(ctx context.Context, arg HasActiveDuplicateContentParams) (bool, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// ON CONFLICT DO NOTHING rather than an upsert: two processes booting at once
	// must not each mint a DEK and have the second overwrite the first, because
	// anything the loser sealed in between would become unopenable. The conflicting
	// caller gets no row back and re-reads the winner's key instead — see
	// LoadOrCreateDataKey.
	InsertDataKey(ctx context.Context, arg InsertDataKeyParams) (DataKey, error)
	InsertFact(ctx context.Context, arg InsertFactParams) (InsertFactRow, error)
	InsertFactScope(ctx context.Context, arg InsertFactScopeParams) error
	InsertGrant(ctx context.Context, arg InsertGrantParams) (Grant, error)
	// Database-generated columns only; see InsertStagedDiff for why. The rest is
	// the caller's own input, and returning `justification` in particular meant the
	// agent role needed SELECT over every subject's stated reasons for wanting a
	// grant.
	InsertGrantRequest(ctx context.Context, arg InsertGrantRequestParams) (InsertGrantRequestRow, error)
	InsertGrantScope(ctx context.Context, arg InsertGrantScopeParams) error
	InsertReviewerToken(ctx context.Context, arg InsertReviewerTokenParams) (InsertReviewerTokenRow, error)
	// Returns only the columns the database generates. Everything else in the row
	// is the caller's own input, so echoing it back is redundant — and it is not
	// free: RETURNING requires SELECT privilege on every column it reads, so a
	// wide RETURNING forced a table-wide SELECT grant for cmd/mcpserver, letting an
	// agent enumerate every other subject's proposed content. Narrow here, and the
	// grant narrows with it (see the least_privilege_roles migration).
	InsertStagedDiff(ctx context.Context, arg InsertStagedDiffParams) (InsertStagedDiffRow, error)
	ListGrantRequests(ctx context.Context, status string) ([]GrantRequest, error)
	ListGrantScopes(ctx context.Context, grantID string) ([]string, error)
	// Scopes come back via an array_agg subquery (same shape as
	// ListGrantsNearingExpiry and GetFact/SearchFacts' fact_scopes aggregation in
	// facts.sql) rather than a separate ListGrantScopes call per row, to avoid an
	// N+1 query per returned grant. Found in review.
	ListGrants(ctx context.Context, subject string) ([]ListGrantsRow, error)
	// Subject-agnostic by design, like ListStagedDiffs/ListGrantRequests — v0 is a
	// single-operator system (AGENTS.md), so the expiry-warning SSE stream isn't
	// scoped per subject either.
	//
	// Scopes come back via an array_agg subquery (same shape as GetFact/
	// SearchFacts' fact_scopes aggregation in facts.sql) rather than a separate
	// ListGrantScopes call per row: this query runs from the /api/events poll
	// loop, potentially every eventPollInterval per connected SSE client, so an
	// N+1 pattern here scales with (expiring grants) x (connected clients) x
	// (polls/sec) — worth avoiding at the query level rather than in a hot loop.
	// Found in review.
	ListGrantsNearingExpiry(ctx context.Context, expiresAt pgtype.Timestamptz) ([]ListGrantsNearingExpiryRow, error)
	ListReviewerTokens(ctx context.Context) ([]ListReviewerTokensRow, error)
	ListStagedDiffs(ctx context.Context, status string) ([]StagedDiff, error)
	LoadGrantRequestForUpdate(ctx context.Context, id string) (LoadGrantRequestForUpdateRow, error)
	LoadStagedDiffForUpdate(ctx context.Context, id string) (LoadStagedDiffForUpdateRow, error)
	LockTargetFact(ctx context.Context, id string) (*time.Time, error)
	LookupActiveReviewerToken(ctx context.Context, tokenHash []byte) (LookupActiveReviewerTokenRow, error)
	MarkDiffCommitted(ctx context.Context, arg MarkDiffCommittedParams) error
	RejectDiff(ctx context.Context, arg RejectDiffParams) (int64, error)
	// Only a currently-active grant (not revoked, not already past its expiry) can
	// be renewed — zero rows affected (surfaced by sqlc as pgx.ErrNoRows for a
	// :one query) covers "doesn't exist," "already revoked," and "already
	// expired" alike; store.RenewGrant turns that into one clear error.
	//
	// kind = 'memory' is deliberate, not incidental. Renewal was built for memory
	// grants, and extending a *capability* grant is a materially different act:
	// capability renewal has to answer what happens to key material held for the
	// grant's duration, whether the custody backend must be reachable to renew,
	// and whether a renewal is a fresh authorization decision rather than a date
	// change. None of that is designed yet. Until the broker answers it, a
	// capability grant is renewed by not being renewable — deliberately, rather
	// than inheriting memory's semantics by omission. Nothing can create one
	// today (both API and MCP hardcode kind='memory'), so this filter is a latch
	// closed before the door exists, not a live fix.
	RenewGrant(ctx context.Context, arg RenewGrantParams) (Grant, error)
	RevokeGrant(ctx context.Context, id string) (int64, error)
	RevokeReviewerToken(ctx context.Context, id string) (int64, error)
	// Master-key rotation: replaces the wrapping without touching anything sealed
	// under the DEK itself. The DEK's plaintext bytes are unchanged by definition,
	// so no data is re-encrypted.
	RewrapDataKey(ctx context.Context, arg RewrapDataKeyParams) (int64, error)
	// LEFT JOIN, not JOIN: source_staged_diff_id is NOT NULL and FK-enforced today,
	// so this always matches, but a provenance projection shouldn't be able to drop
	// an otherwise-visible fact from the result set if that ever changes.
	SearchFacts(ctx context.Context, arg SearchFactsParams) ([]SearchFactsRow, error)
	SupersedeFact(ctx context.Context, arg SupersedeFactParams) error
	TouchReviewerToken(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
