// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"time"
)

type Querier interface {
	FactVisibleToScopes(ctx context.Context, arg FactVisibleToScopesParams) (bool, error)
	// embedding_1/embedding_2 are the same repeated-named-param workaround used
	// elsewhere in this migration (see facts.sql's SearchFacts) — bound to the
	// identical value at the call site.
	FindDedupeCandidate(ctx context.Context, arg FindDedupeCandidateParams) (FindDedupeCandidateRow, error)
	GetFact(ctx context.Context, id string) (GetFactRow, error)
	GetStagedDiff(ctx context.Context, id string) (StagedDiff, error)
	GrantedScopes(ctx context.Context, subject string) ([]string, error)
	// Two distinct named params bound to the identical exclude-fact-ID value at the
	// call site (see staged_diffs.go) — sqlc's parser doesn't handle referencing the
	// same named param twice cleanly in this position (same issue worked around in
	// facts.sql's SearchFacts).
	HasActiveDuplicateContent(ctx context.Context, arg HasActiveDuplicateContentParams) (bool, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertFact(ctx context.Context, arg InsertFactParams) (InsertFactRow, error)
	InsertFactScope(ctx context.Context, arg InsertFactScopeParams) error
	InsertGrant(ctx context.Context, arg InsertGrantParams) (Grant, error)
	InsertGrantScope(ctx context.Context, arg InsertGrantScopeParams) error
	InsertStagedDiff(ctx context.Context, arg InsertStagedDiffParams) (InsertStagedDiffRow, error)
	ListGrantScopes(ctx context.Context, grantID string) ([]string, error)
	ListGrants(ctx context.Context, subject string) ([]Grant, error)
	ListStagedDiffs(ctx context.Context, status string) ([]StagedDiff, error)
	LoadStagedDiffForUpdate(ctx context.Context, id string) (LoadStagedDiffForUpdateRow, error)
	LockTargetFact(ctx context.Context, id string) (*time.Time, error)
	MarkDiffCommitted(ctx context.Context, arg MarkDiffCommittedParams) error
	RejectDiff(ctx context.Context, arg RejectDiffParams) (int64, error)
	RevokeGrant(ctx context.Context, id string) (int64, error)
	SearchFacts(ctx context.Context, arg SearchFactsParams) ([]SearchFactsRow, error)
	SupersedeFact(ctx context.Context, arg SupersedeFactParams) error
}

var _ Querier = (*Queries)(nil)
