// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const incrementProposeWriteRateLimit = `-- name: IncrementProposeWriteRateLimit :one
INSERT INTO propose_write_rate_limits (subject, window_start, count)
VALUES ($1, $2, 1)
ON CONFLICT (subject, window_start)
DO UPDATE SET count = propose_write_rate_limits.count + 1
RETURNING count
`

type IncrementProposeWriteRateLimitParams struct {
	Subject     string
	WindowStart pgtype.Timestamptz
}

// Atomically increments subject's counter for the given fixed window and
// returns the post-increment count. ON CONFLICT DO UPDATE, not a separate
// SELECT-then-INSERT/UPDATE: Postgres serializes concurrent upserts against
// the same (subject, window_start) row via that row's own lock, which is what
// closes the race between two concurrent proposals from the same subject —
// see store.CheckProposeWriteRateLimit's doc comment.
func (q *Queries) IncrementProposeWriteRateLimit(ctx context.Context, arg IncrementProposeWriteRateLimitParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementProposeWriteRateLimit, arg.Subject, arg.WindowStart)
	var count int32
	err := row.Scan(&count)
	return count, err
}
