// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviewer_tokens.sql

package sqlcgen

import (
	"context"
	"time"
)

const countActiveReviewerTokens = `-- name: CountActiveReviewerTokens :one
SELECT count(*) FROM reviewer_tokens WHERE revoked_at IS NULL
`

func (q *Queries) CountActiveReviewerTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveReviewerTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReviewerTOTPSecret = `-- name: GetReviewerTOTPSecret :one
SELECT totp_secret FROM reviewer_tokens WHERE id = $1
`

func (q *Queries) GetReviewerTOTPSecret(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getReviewerTOTPSecret, id)
	var totp_secret *string
	err := row.Scan(&totp_secret)
	return totp_secret, err
}

const insertReviewerToken = `-- name: InsertReviewerToken :one
INSERT INTO reviewer_tokens (label, token_hash, totp_secret)
VALUES ($1, $2, $3)
RETURNING id, label, created_at
`

type InsertReviewerTokenParams struct {
	Label      string
	TokenHash  []byte
	TotpSecret *string
}

type InsertReviewerTokenRow struct {
	ID        string
	Label     string
	CreatedAt time.Time
}

func (q *Queries) InsertReviewerToken(ctx context.Context, arg InsertReviewerTokenParams) (InsertReviewerTokenRow, error) {
	row := q.db.QueryRow(ctx, insertReviewerToken, arg.Label, arg.TokenHash, arg.TotpSecret)
	var i InsertReviewerTokenRow
	err := row.Scan(&i.ID, &i.Label, &i.CreatedAt)
	return i, err
}

const listReviewerTokens = `-- name: ListReviewerTokens :many
SELECT id, label, created_at, last_used_at, revoked_at FROM reviewer_tokens ORDER BY created_at ASC
`

type ListReviewerTokensRow struct {
	ID         string
	Label      string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

func (q *Queries) ListReviewerTokens(ctx context.Context) ([]ListReviewerTokensRow, error) {
	rows, err := q.db.Query(ctx, listReviewerTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewerTokensRow
	for rows.Next() {
		var i ListReviewerTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupActiveReviewerToken = `-- name: LookupActiveReviewerToken :one
SELECT id, label FROM reviewer_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

type LookupActiveReviewerTokenRow struct {
	ID    string
	Label string
}

func (q *Queries) LookupActiveReviewerToken(ctx context.Context, tokenHash []byte) (LookupActiveReviewerTokenRow, error) {
	row := q.db.QueryRow(ctx, lookupActiveReviewerToken, tokenHash)
	var i LookupActiveReviewerTokenRow
	err := row.Scan(&i.ID, &i.Label)
	return i, err
}

const revokeReviewerToken = `-- name: RevokeReviewerToken :execrows
UPDATE reviewer_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeReviewerToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeReviewerToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchReviewerToken = `-- name: TouchReviewerToken :exec
UPDATE reviewer_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchReviewerToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchReviewerToken, id)
	return err
}
