// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signing_policies.sql

package sqlcgen

import (
	"context"
)

const getSigningPolicy = `-- name: GetSigningPolicy :one
SELECT repo, policy, set_by, created_at, updated_at FROM signing_policies WHERE repo = $1
`

func (q *Queries) GetSigningPolicy(ctx context.Context, repo string) (SigningPolicy, error) {
	row := q.db.QueryRow(ctx, getSigningPolicy, repo)
	var i SigningPolicy
	err := row.Scan(
		&i.Repo,
		&i.Policy,
		&i.SetBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSigningPolicy = `-- name: UpsertSigningPolicy :one
INSERT INTO signing_policies (repo, policy, set_by)
VALUES ($1, $2, $3)
ON CONFLICT (repo) DO UPDATE
SET policy = EXCLUDED.policy, set_by = EXCLUDED.set_by, updated_at = now()
RETURNING repo, policy, set_by, created_at, updated_at
`

type UpsertSigningPolicyParams struct {
	Repo   string
	Policy string
	SetBy  string
}

// One row per repo: a second upsert for the same repo replaces the previous
// policy and set_by rather than erroring, matching how a reviewer actually
// changes their mind about a policy (set again, not "unset then set"). The
// audit trail for who changed it and when lives in audit_log, written by
// store.UpsertSigningPolicy in the same transaction — this row only ever
// reflects the current value.
func (q *Queries) UpsertSigningPolicy(ctx context.Context, arg UpsertSigningPolicyParams) (SigningPolicy, error) {
	row := q.db.QueryRow(ctx, upsertSigningPolicy, arg.Repo, arg.Policy, arg.SetBy)
	var i SigningPolicy
	err := row.Scan(
		&i.Repo,
		&i.Policy,
		&i.SetBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
