// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staged_diffs.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const factVisibleToScopes = `-- name: FactVisibleToScopes :one
SELECT EXISTS (
    SELECT 1 FROM facts f
    WHERE f.id = $1
      AND f.invalid_at IS NULL
      AND EXISTS (SELECT 1 FROM fact_scopes fs WHERE fs.fact_id = f.id)
      AND NOT EXISTS (
          SELECT 1 FROM fact_scopes fs
          WHERE fs.fact_id = f.id
            AND NOT (fs.scope = ANY($2::text[]) OR fs.scope LIKE ANY($3::text[]))
      )
) AS visible
`

type FactVisibleToScopesParams struct {
	FactID        string
	GrantedScopes []string
	ScopePrefixes []string
}

func (q *Queries) FactVisibleToScopes(ctx context.Context, arg FactVisibleToScopesParams) (bool, error) {
	row := q.db.QueryRow(ctx, factVisibleToScopes, arg.FactID, arg.GrantedScopes, arg.ScopePrefixes)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const findDedupeCandidate = `-- name: FindDedupeCandidate :one
SELECT f.id, f.content, f.embedding <=> $1::vector AS distance
FROM facts f
WHERE f.invalid_at IS NULL AND f.embedding IS NOT NULL
  AND EXISTS (SELECT 1 FROM fact_scopes fs WHERE fs.fact_id = f.id)
  AND NOT EXISTS (
      SELECT 1 FROM fact_scopes fs
      WHERE fs.fact_id = f.id
        AND NOT (fs.scope = ANY($2::text[]) OR fs.scope LIKE ANY($3::text[]))
  )
ORDER BY f.embedding <=> $4::vector
LIMIT 1
`

type FindDedupeCandidateParams struct {
	Embedding1    pgvector.Vector
	GrantedScopes []string
	ScopePrefixes []string
	Embedding2    pgvector.Vector
}

type FindDedupeCandidateRow struct {
	ID       string
	Content  string
	Distance pgtype.Float8
}

// embedding_1/embedding_2 are the same repeated-named-param workaround used
// elsewhere in this migration (see facts.sql's SearchFacts) — bound to the
// identical value at the call site.
func (q *Queries) FindDedupeCandidate(ctx context.Context, arg FindDedupeCandidateParams) (FindDedupeCandidateRow, error) {
	row := q.db.QueryRow(ctx, findDedupeCandidate,
		arg.Embedding1,
		arg.GrantedScopes,
		arg.ScopePrefixes,
		arg.Embedding2,
	)
	var i FindDedupeCandidateRow
	err := row.Scan(&i.ID, &i.Content, &i.Distance)
	return i, err
}

const getStagedDiff = `-- name: GetStagedDiff :one
SELECT id, subject, content, proposed_scopes, target_fact_id, status,
       dedupe_verdict, dedupe_candidate_fact_id, created_at, decided_at, decided_by
FROM staged_diffs WHERE id = $1
`

func (q *Queries) GetStagedDiff(ctx context.Context, id string) (StagedDiff, error) {
	row := q.db.QueryRow(ctx, getStagedDiff, id)
	var i StagedDiff
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Content,
		&i.ProposedScopes,
		&i.TargetFactID,
		&i.Status,
		&i.DedupeVerdict,
		&i.DedupeCandidateFactID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const hasActiveDuplicateContent = `-- name: HasActiveDuplicateContent :one
SELECT EXISTS (
    SELECT 1 FROM facts
    WHERE invalid_at IS NULL AND content = $1
      AND ($2::uuid IS NULL OR id != $3)
) AS has_duplicate
`

type HasActiveDuplicateContentParams struct {
	Content        string
	ExcludeFactID1 *string
	ExcludeFactID2 *string
}

// Two distinct named params bound to the identical exclude-fact-ID value at the
// call site (see staged_diffs.go) — sqlc's parser doesn't handle referencing the
// same named param twice cleanly in this position (same issue worked around in
// facts.sql's SearchFacts).
func (q *Queries) HasActiveDuplicateContent(ctx context.Context, arg HasActiveDuplicateContentParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveDuplicateContent, arg.Content, arg.ExcludeFactID1, arg.ExcludeFactID2)
	var has_duplicate bool
	err := row.Scan(&has_duplicate)
	return has_duplicate, err
}

const insertFact = `-- name: InsertFact :one
INSERT INTO facts (content, summary, embedding, source_staged_diff_id)
VALUES ($1, $2, $3, $4)
RETURNING id, content, summary, created_at, valid_at
`

type InsertFactParams struct {
	Content            string
	Summary            *string
	Embedding          *pgvector.Vector
	SourceStagedDiffID string
}

type InsertFactRow struct {
	ID        string
	Content   string
	Summary   *string
	CreatedAt time.Time
	ValidAt   time.Time
}

func (q *Queries) InsertFact(ctx context.Context, arg InsertFactParams) (InsertFactRow, error) {
	row := q.db.QueryRow(ctx, insertFact,
		arg.Content,
		arg.Summary,
		arg.Embedding,
		arg.SourceStagedDiffID,
	)
	var i InsertFactRow
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Summary,
		&i.CreatedAt,
		&i.ValidAt,
	)
	return i, err
}

const insertFactScope = `-- name: InsertFactScope :exec
INSERT INTO fact_scopes (fact_id, scope) VALUES ($1, $2)
`

type InsertFactScopeParams struct {
	FactID string
	Scope  string
}

func (q *Queries) InsertFactScope(ctx context.Context, arg InsertFactScopeParams) error {
	_, err := q.db.Exec(ctx, insertFactScope, arg.FactID, arg.Scope)
	return err
}

const insertStagedDiff = `-- name: InsertStagedDiff :one
INSERT INTO staged_diffs (subject, content, proposed_scopes, target_fact_id, dedupe_verdict, dedupe_candidate_fact_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, subject, content, proposed_scopes, target_fact_id, status, dedupe_verdict, dedupe_candidate_fact_id, created_at
`

type InsertStagedDiffParams struct {
	Subject               string
	Content               string
	ProposedScopes        []string
	TargetFactID          *string
	DedupeVerdict         *string
	DedupeCandidateFactID *string
}

type InsertStagedDiffRow struct {
	ID                    string
	Subject               string
	Content               string
	ProposedScopes        []string
	TargetFactID          *string
	Status                string
	DedupeVerdict         *string
	DedupeCandidateFactID *string
	CreatedAt             time.Time
}

func (q *Queries) InsertStagedDiff(ctx context.Context, arg InsertStagedDiffParams) (InsertStagedDiffRow, error) {
	row := q.db.QueryRow(ctx, insertStagedDiff,
		arg.Subject,
		arg.Content,
		arg.ProposedScopes,
		arg.TargetFactID,
		arg.DedupeVerdict,
		arg.DedupeCandidateFactID,
	)
	var i InsertStagedDiffRow
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Content,
		&i.ProposedScopes,
		&i.TargetFactID,
		&i.Status,
		&i.DedupeVerdict,
		&i.DedupeCandidateFactID,
		&i.CreatedAt,
	)
	return i, err
}

const listStagedDiffs = `-- name: ListStagedDiffs :many
SELECT id, subject, content, proposed_scopes, target_fact_id, status,
       dedupe_verdict, dedupe_candidate_fact_id, created_at, decided_at, decided_by
FROM staged_diffs WHERE status = $1 ORDER BY created_at ASC
`

func (q *Queries) ListStagedDiffs(ctx context.Context, status string) ([]StagedDiff, error) {
	rows, err := q.db.Query(ctx, listStagedDiffs, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StagedDiff
	for rows.Next() {
		var i StagedDiff
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Content,
			&i.ProposedScopes,
			&i.TargetFactID,
			&i.Status,
			&i.DedupeVerdict,
			&i.DedupeCandidateFactID,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadStagedDiffForUpdate = `-- name: LoadStagedDiffForUpdate :one
SELECT content, proposed_scopes, target_fact_id, status
FROM staged_diffs WHERE id = $1 FOR UPDATE
`

type LoadStagedDiffForUpdateRow struct {
	Content        string
	ProposedScopes []string
	TargetFactID   *string
	Status         string
}

func (q *Queries) LoadStagedDiffForUpdate(ctx context.Context, id string) (LoadStagedDiffForUpdateRow, error) {
	row := q.db.QueryRow(ctx, loadStagedDiffForUpdate, id)
	var i LoadStagedDiffForUpdateRow
	err := row.Scan(
		&i.Content,
		&i.ProposedScopes,
		&i.TargetFactID,
		&i.Status,
	)
	return i, err
}

const lockTargetFact = `-- name: LockTargetFact :one
SELECT invalid_at FROM facts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockTargetFact(ctx context.Context, id string) (*time.Time, error) {
	row := q.db.QueryRow(ctx, lockTargetFact, id)
	var invalid_at *time.Time
	err := row.Scan(&invalid_at)
	return invalid_at, err
}

const markDiffCommitted = `-- name: MarkDiffCommitted :exec
UPDATE staged_diffs SET status = 'committed', decided_at = now(), decided_by = $2 WHERE id = $1
`

type MarkDiffCommittedParams struct {
	ID        string
	DecidedBy *string
}

func (q *Queries) MarkDiffCommitted(ctx context.Context, arg MarkDiffCommittedParams) error {
	_, err := q.db.Exec(ctx, markDiffCommitted, arg.ID, arg.DecidedBy)
	return err
}

const rejectDiff = `-- name: RejectDiff :execrows
UPDATE staged_diffs SET status = 'rejected', decided_at = now(), decided_by = $2
WHERE id = $1 AND status = 'pending'
`

type RejectDiffParams struct {
	ID        string
	DecidedBy *string
}

func (q *Queries) RejectDiff(ctx context.Context, arg RejectDiffParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectDiff, arg.ID, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeFact = `-- name: SupersedeFact :exec
UPDATE facts SET invalid_at = $1, expired_at = now(), superseded_by = $2
WHERE id = $3
`

type SupersedeFactParams struct {
	InvalidAt    pgtype.Timestamptz
	SupersededBy *string
	TargetID     string
}

func (q *Queries) SupersedeFact(ctx context.Context, arg SupersedeFactParams) error {
	_, err := q.db.Exec(ctx, supersedeFact, arg.InvalidAt, arg.SupersededBy, arg.TargetID)
	return err
}
