// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeWebAuthnChallenge = `-- name: ConsumeWebAuthnChallenge :one
DELETE FROM webauthn_challenges
WHERE reviewer_token_id = $1 AND purpose = $2 AND expires_at > now()
RETURNING session_data
`

type ConsumeWebAuthnChallengeParams struct {
	ReviewerTokenID string
	Purpose         string
}

// DELETE ... RETURNING makes single-use atomic: two concurrent finish calls
// for the same reviewer/purpose can never both see a row, since only one
// DELETE can match it. expires_at > now() folds the short-expiry check into
// the same statement rather than a separate read-then-check that would leave
// a window between them.
func (q *Queries) ConsumeWebAuthnChallenge(ctx context.Context, arg ConsumeWebAuthnChallengeParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, consumeWebAuthnChallenge, arg.ReviewerTokenID, arg.Purpose)
	var session_data []byte
	err := row.Scan(&session_data)
	return session_data, err
}

const countEverEnrolledWebAuthnCredentials = `-- name: CountEverEnrolledWebAuthnCredentials :one
SELECT count(*) FROM webauthn_credentials
`

// Deliberately NOT filtered on revoked_at, mirroring
// CountEverEnrolledReviewerTokens (reviewer_tokens.sql) exactly and for the
// same reason: this feeds createToken's monotonic "has any second factor
// ever been enrolled on this deployment" gate, and an active-only count
// would let bearer-only revocation (of credentials or of their owning
// tokens) reopen that gate. Rows are never deleted by any API path — revoke
// sets revoked_at, and the ON DELETE CASCADE on reviewer_token_id can only
// fire on a reviewer_tokens DELETE, which no API endpoint performs (tokens
// are revoked, never deleted) — so this count only ever grows.
func (q *Queries) CountEverEnrolledWebAuthnCredentials(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEverEnrolledWebAuthnCredentials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const flagWebAuthnCredentialCloneWarning = `-- name: FlagWebAuthnCredentialCloneWarning :exec
UPDATE webauthn_credentials SET clone_warning_at = now(), revoked_at = now() WHERE id = $1
`

// A regressed sign counter is treated as a clone signal and fails closed by
// revoking the credential in the same statement that flags it — a warning
// left live would mean the same possibly-cloned key keeps passing this gate
// on every subsequent call. See the webauthn_credentials migration's comment
// on clone_warning_at.
func (q *Queries) FlagWebAuthnCredentialCloneWarning(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, flagWebAuthnCredentialCloneWarning, id)
	return err
}

const insertWebAuthnCredential = `-- name: InsertWebAuthnCredential :one
INSERT INTO webauthn_credentials
    (reviewer_token_id, label, credential_id, public_key, attestation_type, transports, aaguid, sign_count,
     backup_eligible, backup_state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, reviewer_token_id, label, credential_id, public_key, attestation_type, transports, aaguid,
    sign_count, backup_eligible, backup_state, created_at, last_used_at, clone_warning_at, revoked_at
`

type InsertWebAuthnCredentialParams struct {
	ReviewerTokenID string
	Label           string
	CredentialID    []byte
	PublicKey       []byte
	AttestationType string
	Transports      []string
	Aaguid          []byte
	SignCount       int64
	BackupEligible  bool
	BackupState     bool
}

func (q *Queries) InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, insertWebAuthnCredential,
		arg.ReviewerTokenID,
		arg.Label,
		arg.CredentialID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transports,
		arg.Aaguid,
		arg.SignCount,
		arg.BackupEligible,
		arg.BackupState,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.ReviewerTokenID,
		&i.Label,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transports,
		&i.Aaguid,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.CloneWarningAt,
		&i.RevokedAt,
	)
	return i, err
}

const listWebAuthnCredentialsForReviewer = `-- name: ListWebAuthnCredentialsForReviewer :many
SELECT id, reviewer_token_id, label, credential_id, public_key, attestation_type, transports, aaguid,
    sign_count, backup_eligible, backup_state, created_at, last_used_at, clone_warning_at, revoked_at
FROM webauthn_credentials
WHERE reviewer_token_id = $1
ORDER BY created_at ASC
`

// Returns every credential (active and revoked) owned by one reviewer token,
// oldest first — mirrors ListReviewerTokens's "show history, not just the
// live set" stance. Callers that need only live credentials (building a
// ceremony's allow/exclude list) filter revoked_at in Go rather than a second
// near-identical query — one source of truth for "what does this reviewer
// have" that both the ceremony and the listing endpoint read.
func (q *Queries) ListWebAuthnCredentialsForReviewer(ctx context.Context, reviewerTokenID string) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsForReviewer, reviewerTokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.ReviewerTokenID,
			&i.Label,
			&i.CredentialID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transports,
			&i.Aaguid,
			&i.SignCount,
			&i.BackupEligible,
			&i.BackupState,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.CloneWarningAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewerHasActiveWebAuthnCredential = `-- name: ReviewerHasActiveWebAuthnCredential :one
SELECT EXISTS(
    SELECT 1 FROM webauthn_credentials WHERE reviewer_token_id = $1 AND revoked_at IS NULL
)
`

func (q *Queries) ReviewerHasActiveWebAuthnCredential(ctx context.Context, reviewerTokenID string) (bool, error) {
	row := q.db.QueryRow(ctx, reviewerHasActiveWebAuthnCredential, reviewerTokenID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reviewerHasTOTP = `-- name: ReviewerHasTOTP :one
SELECT totp_secret_enc IS NOT NULL AS has_totp FROM reviewer_tokens WHERE id = $1
`

// Per-reviewer, not the deployment-wide CountEverEnrolledReviewerTokens: this
// answers "does *this* token have a factor to demand", not "has anything ever
// been enrolled" — see requireExistingSecondFactor (internal/api).
func (q *Queries) ReviewerHasTOTP(ctx context.Context, id string) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, reviewerHasTOTP, id)
	var has_totp pgtype.Bool
	err := row.Scan(&has_totp)
	return has_totp, err
}

const revokeWebAuthnCredential = `-- name: RevokeWebAuthnCredential :execrows
UPDATE webauthn_credentials SET revoked_at = now() WHERE id = $1 AND reviewer_token_id = $2 AND revoked_at IS NULL
`

type RevokeWebAuthnCredentialParams struct {
	ID              string
	ReviewerTokenID string
}

func (q *Queries) RevokeWebAuthnCredential(ctx context.Context, arg RevokeWebAuthnCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeWebAuthnCredential, arg.ID, arg.ReviewerTokenID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWebAuthnCredentialCounter = `-- name: UpdateWebAuthnCredentialCounter :exec
UPDATE webauthn_credentials SET sign_count = $2, last_used_at = now() WHERE id = $1
`

type UpdateWebAuthnCredentialCounterParams struct {
	ID        string
	SignCount int64
}

func (q *Queries) UpdateWebAuthnCredentialCounter(ctx context.Context, arg UpdateWebAuthnCredentialCounterParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialCounter, arg.ID, arg.SignCount)
	return err
}

const upsertWebAuthnChallenge = `-- name: UpsertWebAuthnChallenge :exec
INSERT INTO webauthn_challenges (reviewer_token_id, purpose, session_data, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (reviewer_token_id, purpose)
DO UPDATE SET session_data = EXCLUDED.session_data, expires_at = EXCLUDED.expires_at, created_at = now()
`

type UpsertWebAuthnChallengeParams struct {
	ReviewerTokenID string
	Purpose         string
	SessionData     []byte
	ExpiresAt       pgtype.Timestamptz
}

// One pending challenge per (reviewer, purpose): starting a new ceremony
// overwrites whatever the previous, presumably-abandoned one was rather than
// accumulating rows nothing will ever consume.
func (q *Queries) UpsertWebAuthnChallenge(ctx context.Context, arg UpsertWebAuthnChallengeParams) error {
	_, err := q.db.Exec(ctx, upsertWebAuthnChallenge,
		arg.ReviewerTokenID,
		arg.Purpose,
		arg.SessionData,
		arg.ExpiresAt,
	)
	return err
}
